### ISSUE TITLE
只有真正碰到这种问题的人才能明白这个项目有多好

### ISSUE THREAD

**Issue by Folyd** [bells/elasticsearch-analysis-dynamic-synonym#1]
好赞的项目。请问兼容ES 2.3.x版吗？

**Comment by Folyd** [comment]
```
	<groupId>com.bellszhu.elasticsearch</groupId>
	<artifactId>elasticsearch-analysis-dynamic-synonym</artifactId>
	<version>2.3.0</version>
	<packaging>jar</packaging>

	<name>elasticsearch-dynamic-synonym</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<elasticsearch.version>2.3.0</elasticsearch.version>
	</properties>

```
我把pom.xml改了一下，然后`mvn package` 拷贝到ES plugins目录下面，重启ES，报错了
```
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [dynamic-synonym]. Was the plugin built before 2.0?
Likely root cause: java.nio.file.NoSuchFileException: /opt/elasticsearch-2.3.2/plugins/dynamic-synonym/plugin-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:87)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

**Comment by JohnTian** [comment]
@Folyd 最近我也遇到这个问题了，请问你解决了么？

**Comment by bells** [comment]
我这周处理下！

**Comment by bells** [comment]
@Folyd @JohnTian 已经支持2.3.X了。谢谢！
