### ISSUE TITLE
1.6.0版本mvn package失败

### ISSUE THREAD

**Issue by zonglinyue** [bells/elasticsearch-analysis-dynamic-synonym#10]
以下是mvn package 的报错信息。请大神看一下错误原因。
[DEBUG] -d C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\target\classes -classpath C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\target\classes;D:\WorkSpaces\MvnRepository\org\elasticsearch\elasticsearch\1.6.0\elasticsearch-1.6.0.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-core\4.10.4\lucene-core-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-analyzers-common\4.10.4\lucene-analyzers-common-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-queries\4.10.4\lucene-queries-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-memory\4.10.4\lucene-memory-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-highlighter\4.10.4\lucene-highlighter-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-queryparser\4.10.4\lucene-queryparser-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-sandbox\4.10.4\lucene-sandbox-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-suggest\4.10.4\lucene-suggest-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-misc\4.10.4\lucene-misc-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-join\4.10.4\lucene-join-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-grouping\4.10.4\lucene-grouping-4.10.4.jar;D:\WorkSpaces\MvnRepository\org\apache\lucene\lucene-spatial\4.10.4\lucene-spatial-4.10.4.jar;D:\WorkSpaces\MvnRepository\com\spatial4j\spatial4j\0.4.1\spatial4j-0.4.1.jar;D:\WorkSpaces\MvnRepository\org\antlr\antlr-runtime\3.5\antlr-runtime-3.5.jar;D:\WorkSpaces\MvnRepository\org\ow2\asm\asm\4.1\asm-4.1.jar;D:\WorkSpaces\MvnRepository\org\ow2\asm\asm-commons\4.1\asm-commons-4.1.jar;D:\WorkSpaces\MvnRepository\org\yaml\snakeyaml\1.12\snakeyaml-1.12.jar;D:\WorkSpaces\MvnRepository\org\apache\httpcomponents\httpclient\4.4.1\httpclient-4.4.1.jar;D:\WorkSpaces\MvnRepository\org\apache\httpcomponents\httpcore\4.4.1\httpcore-4.4.1.jar;D:\WorkSpaces\MvnRepository\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;D:\WorkSpaces\MvnRepository\commons-codec\commons-codec\1.9\commons-codec-1.9.jar; -sourcepath C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java; C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\LocalSynonymFile.java C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\DynamicSynonymFilter.java C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\RemoteSynonymFile.java C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\DynamicSynonymPlugin.java C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\DynamicSynonymTokenFilterFactory.java C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\SynonymFile.java -s C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\target\generated-sources\annotations -g -nowarn -target 1.6 -source 1.6 -encoding UTF-8
[INFO] Compiling 6 source files to C:\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\DynamicSynonymFilter.java:[699,27] 错误: -source 1.6 中不支持 diamond 运算符
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.564 s
[INFO] Finished at: 2016-12-14T18:29:34+08:00
[INFO] Final Memory: 11M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project elasticsearch-analysis-dynamic-synonym: Compilation failure
[ERROR] \Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\DynamicSynonymFilter.java:[699,27] 错误: -source 1.6 中不支持 diamond 运算符
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project elasticsearch-analysis-dynamic-synonym: Compilation failure
\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\DynamicSynonymFilter.java:[699,27] 错误: -source 1.6 中不支持 diamond 运算符

        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
\Users\YUE\Desktop\elasticsearch-analysis-dynamic-synonym-1.6.0\src\main\java\com\bellszhu\elasticsearch\plugin\synonym\analysis\DynamicSynonymFilter.java:[699,27] 错误: -source 1.6 中不支持 diamond 运算符

        at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:656)
        at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by bells** [comment]
@zonglinyue 用jdk1.7

**Comment by zonglinyue** [comment]
我换到1.7.0_80版本jdk，还是报错。请问您用的那个版本的jdk？或者您发我一个打包好的文件。非常感谢！
