### ISSUE TITLE
master主分支不支持elasticsearch 7.17.5

### ISSUE THREAD

**Issue by cantgis** [bells/elasticsearch-analysis-dynamic-synonym#108]
Exception in thread "main" java.nio.file.NoSuchFileException: /opt/elasticsearch/plugins/.installing-7857110605207267854/plugin-descriptor.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at org.elasticsearch.plugins.PluginDescriptor.readFromProperties(PluginDescriptor.java:183)
	at org.elasticsearch.plugins.cli.InstallPluginAction.loadPluginInfo(InstallPluginAction.java:827)
	at org.elasticsearch.plugins.cli.InstallPluginAction.installPlugin(InstallPluginAction.java:887)
	at org.elasticsearch.plugins.cli.InstallPluginAction.execute(InstallPluginAction.java:245)
	at org.elasticsearch.plugins.cli.InstallPluginCommand.execute(InstallPluginCommand.java:88)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:95)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at org.elasticsearch.cli.Command.main(Command.java:77)
	at org.elasticsearch.plugins.cli.PluginCli.main(PluginCli.java:36)

**Comment by ColorfulDick** [comment]
林北，我改成比较新的8.2.3，也不行，打包都打不了

**Comment by hidden-lii** [comment]
测试了一下目前master分支7.17.5可以成功打包，而且在es上正常运行
