### ISSUE TITLE
Premature end of Content-Length delimited message body 

### ISSUE THREAD

**Issue by platstar** [bells/elasticsearch-analysis-dynamic-synonym#21]
已经配置好，但是远程请求txt文件报错
elasticsearch 2.4.3

`[2017-03-07 14:01:35,553][INFO ][node                     ] [node.9202.243] started
[2017-03-07 14:01:36,553][INFO ][dynamic-synonym          ] start reload remote synonym from http://192.168.57.15/xxx/synonym/getdata.
[2017-03-07 14:01:36,569][ERROR][dynamic-synonym          ] reload remote synonym http://192.168.57.15/xxx/synonym/getdata error!
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 229; received: 0
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:142)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:120)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:266)
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at org.apache.http.client.protocol.ResponseContentEncoding$1.create(ResponseContentEncoding.java:67)
        at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:54)
        at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:72)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.LineNumberReader.readLine(LineNumberReader.java:201)
        at org.apache.lucene.analysis.synonym.SolrSynonymParser.addInternal(SolrSynonymParser.java:82)
        at org.apache.lucene.analysis.synonym.SolrSynonymParser.parse(SolrSynonymParser.java:70)
        at com.bellszhu.elasticsearch.plugin.synonym.analysis.RemoteSynonymFile.reloadSynonymMap(RemoteSynonymFile.java:75)
        at com.bellszhu.elasticsearch.plugin.synonym.analysis.DynamicSynonymTokenFilterFactory.<init>(DynamicSynonymTokenFilterFactory.java:120)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
`

**Comment by platstar** [comment]
`
index:
  analysis:
    filter:
      remote_synonym:
          type: dynamic_synonym
          synonyms_path: http://192.168.57.15/xxx/synonym/getdata
          interval: 30
      local_synonym:
          type: dynamic_synonym
          synonyms_path: analysis/synonym.txt
 `
也試過      #synonyms_path: http://192.168.57.15/xxx.synonym.txt 
結果一樣報錯

**Comment by lzg406** [comment]
BUG，处理请求回来流之前已经关闭了response
