### ISSUE TITLE
请问只支持你提供的这几个版本吗？2.3.4或2.3.6不支持吗？

### ISSUE THREAD

**Issue by tyw809611051** [bells/elasticsearch-analysis-dynamic-synonym#27]
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-dynamic-synonym] is incompatible with Elasticsearch [2.3.4]. Was designed for version [5.2.0]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:118)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:378)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:128)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by wuhulala** [comment]
这个可以自己修改es版本的 
pom.xml
```xml
<elasticsearch.version>5.2.0</elasticsearch.version>
```
